/-!
Effect-independence framework (paper Section 3.1.3, Definitions 17-21).
Unlike `Basic.lean`'s `Registry`/`Fiber` model -- which elides an
effect's computational content down to "installs `provides`" -- this
file states Definitions 17-21 over a genuine abstract state type `Gamma`
and genuine `Gamma -> Gamma` effect functions, the level the paper's
own statements live at. Reducing the framework to `Registry`'s own
elided `e` would only produce a vacuous "every abstract effect
trivially commutes" restatement (see `calculus.rs`'s header comment on
why it originally scoped Section 3.1 out); this file closes that gap,
proving the framework's OWN algebraic content for every possible state
type and every possible finite family of effects, independent of which
concrete `Gamma` a future gm-specific port would choose.

No external monoid/group-theory library is used (this project has zero
Lean dependencies, `lake-manifest.json`'s `packages` is empty) -- the
transformation monoid of Definition 17 is modeled directly as an
inductive closure predicate over `Gamma -> Gamma`, generated by a
finite list of seed maps under composition and identity, checked by the
same plain structural induction `Basic.lean`/`Confluence.lean` already
use throughout this project.

A revertible effect (Definition 17's premise) is a forward map paired
with, at every state it can reach, an inverse map for that specific
reachable state -- an effect's inverse is state-DEPENDENT in general
(undoing "set x to 5" from state s needs to know what x was in s),
which is why Definition 17 generates `M(e)` from both the forward map
and the whole FAMILY of state-indexed inverses, not from one global
inverse function.
-/

variable {Gamma : Type}

/-- A revertible effect (Definition 17's premise): a forward
transformer `fwd : Gamma -> Gamma` together with, for every state, an
inverse transformer for the transition FROM that state -- `inv s`
undoes exactly the transition `fwd` would apply starting at `s`. The
defining law `left_inv` is `inv s (fwd s) = s`. -/
structure RevertibleEffect (Gamma : Type) where
  fwd : Gamma → Gamma
  inv : Gamma → Gamma → Gamma
  left_inv : ∀ s, inv s (fwd s) = s

/-- The finite generating set Definition 17 names for a revertible
effect `e`: the forward map, plus the inverse map indexed by every
state in a caller-supplied finite `reachable` list (a real deployment's
generating set is finite because only finitely many states are ever
actually visited in one run; `reachable` stands in for "every state `e`
is applied at across the run being reasoned about," never claimed to
be every state of `Gamma`). -/
def RevertibleEffect.generators (e : RevertibleEffect Gamma) (reachable : List Gamma) :
    List (Gamma → Gamma) :=
  e.fwd :: reachable.map e.inv

/-- Definition 17: the transformation monoid `M(e)` generated by a
finite seed list `gens` under function composition -- the smallest set
of `Gamma -> Gamma` maps containing `gens`, closed under identity and
composition. Modeled as an inductive membership predicate rather than a
`Set`/`Submonoid` (no such library is available), mirroring the shape
`Registry.wellFormed`/`Registry.satisfied` already use in this
project: a `Prop`-valued closure defined by its own introduction rules,
checked by induction. -/
inductive InMonoid (gens : List (Gamma → Gamma)) : (Gamma → Gamma) → Prop where
  | gen : ∀ f, f ∈ gens → InMonoid gens f
  | id : InMonoid gens id
  | comp : ∀ f g, InMonoid gens f → InMonoid gens g → InMonoid gens (f ∘ g)

/-- Two endomorphisms of `Gamma` commute under composition -- the
notion Definition 18/Lemma 18 states "every generator of `M(e1)`
commutes with every generator of `M(e2)`" in terms of. -/
def Commuting (f g : Gamma → Gamma) : Prop := f ∘ g = g ∘ f

theorem Commuting.symm {f g : Gamma → Gamma} (h : Commuting f g) : Commuting g f := Eq.symm h

theorem commuting_id_left (f : Gamma → Gamma) : Commuting (id : Gamma → Gamma) f := rfl
theorem commuting_id_right (f : Gamma → Gamma) : Commuting f (id : Gamma → Gamma) := rfl

theorem commuting_comp_left {f1 f2 g : Gamma → Gamma}
    (h1 : Commuting f1 g) (h2 : Commuting f2 g) : Commuting (f1 ∘ f2) g := by
  funext s
  show f1 (f2 (g s)) = g (f1 (f2 s))
  have e2 : f2 (g s) = g (f2 s) := congrFun h2 s
  rw [e2]
  exact congrFun h1 (f2 s)

theorem commuting_comp_right {f g1 g2 : Gamma → Gamma}
    (h1 : Commuting f g1) (h2 : Commuting f g2) : Commuting f (g1 ∘ g2) :=
  (commuting_comp_left h1.symm h2.symm).symm

/-- Lemma 18: if every GENERATOR of `M(e1)` (drawn from `gens1`)
commutes with every GENERATOR of `M(e2)` (drawn from `gens2`), then
every ELEMENT of `M(e1)` commutes with every element of `M(e2)` --
commutation lifts from a generating set to the whole closure. Proved
by nested induction on the two `InMonoid` derivations, using
`commuting_id_left/right` for the identity case and
`commuting_comp_left/right` to push commutation through composition;
this is the load-bearing lemma Theorem 20 rests on, since it lets
"independent effects commute" be CHECKED on the small, syntactically
given generating lists rather than on the possibly-large monoid
closures. -/
theorem commuting_of_generators_commuting
    {gens1 gens2 : List (Gamma → Gamma)}
    (hcomm : ∀ g1 ∈ gens1, ∀ g2 ∈ gens2, Commuting g1 g2) :
    ∀ f1, InMonoid gens1 f1 → ∀ f2, InMonoid gens2 f2 → Commuting f1 f2 := by
  intro f1 hf1
  induction hf1 with
  | gen g1 hg1 =>
    intro f2 hf2
    induction hf2 with
    | gen g2 hg2 => exact hcomm g1 hg1 g2 hg2
    | id => exact commuting_id_right g1
    | comp x y _ _ ihx ihy => exact commuting_comp_right ihx ihy
  | id =>
    intro f2 _
    exact commuting_id_left f2
  | comp x y _ _ ihx ihy =>
    intro f2 hf2
    exact commuting_comp_left (ihx f2 hf2) (ihy f2 hf2)

/-- Definition 19 clause (a): every transformation `M(e1)` can perform
commutes with every transformation `M(e2)` can perform, relative to
finite generating lists for each. -/
def MonoidsCommute (gens1 gens2 : List (Gamma → Gamma)) : Prop :=
  ∀ f1, InMonoid gens1 f1 → ∀ f2, InMonoid gens2 f2 → Commuting f1 f2

/-- Definition 19 clause (b): applying any transformation `f1` drawn
from `e1`'s monoid never disturbs the inverse `e2` would produce for a
state -- concretely, `e2`'s inverse evaluated AT the state `f1`
produced (`e2.inv (f1 s)`), applied to whatever `e2.fwd` would compute
starting from a DIFFERENT, arbitrary target state `t`, agrees with
running `f1` first and then reading `e2`'s inverse-at-`t` from the
original (pre-`f1`) side: `e2.inv (f1 s) (f1 t) = f1 (e2.inv s t)`.
Read at `t := e2.fwd s`, `left_inv` collapses this to a triviality (both
sides become `f1 s`, independent of whether `f1` "disturbs" anything),
which is exactly why the clause is stated for an ARBITRARY `t`, not
only the specific final state `e2.fwd s` -- an arbitrary `t` is what
makes the clause say `f1` and `e2.inv s` genuinely commute AS
FUNCTIONS OF THE SECOND ARGUMENT, the real "does not corrupt the other
effect's undo data" content: `e2`'s inverse-computation, viewed as a
function from a target state to a source state, factors through `f1`
the same way regardless of whether `f1` was applied before or the
inverse-data is read before `f1` runs. This is genuinely non-vacuous
(unlike a same-`t`-only reading, which collapses to `RevertibleEffect`'s
own `left_inv` law and says nothing new about `e1`/`e2` jointly). -/
def InverseUndisturbed (gens1 : List (Gamma → Gamma)) (e2 : RevertibleEffect Gamma) : Prop :=
  ∀ f1, InMonoid gens1 f1 → ∀ s t : Gamma, e2.inv (f1 s) (f1 t) = f1 (e2.inv s t)

/-- Definition 19: independence, the conjunction of both clauses, for a
pair of revertible effects together with their chosen finite generating
lists. -/
structure Independent (e1 e2 : RevertibleEffect Gamma)
    (gens1 gens2 : List (Gamma → Gamma)) : Prop where
  commute : MonoidsCommute (Gamma := Gamma) gens1 gens2
  undisturbed12 : InverseUndisturbed gens1 e2
  undisturbed21 : InverseUndisturbed gens2 e1

theorem Independent.symm {e1 e2 : RevertibleEffect Gamma} {gens1 gens2 : List (Gamma → Gamma)}
    (h : Independent e1 e2 gens1 gens2) : Independent e2 e1 gens2 gens1 :=
  { commute := fun f2 hf2 f1 hf1 => (h.commute f1 hf1 f2 hf2).symm
    undisturbed12 := h.undisturbed21
    undisturbed21 := h.undisturbed12 }

/-- Independence via generator-level commutation, the practical route
Lemma 18 exists to license: rather than proving `MonoidsCommute`
directly (a statement over two closures), it suffices to check
commutation on the finite generating lists, plus both
undisturbed-inverse clauses stated over those same lists. -/
theorem independent_of_generators
    (e1 e2 : RevertibleEffect Gamma) (gens1 gens2 : List (Gamma → Gamma))
    (hcomm : ∀ g1 ∈ gens1, ∀ g2 ∈ gens2, Commuting g1 g2)
    (hu12 : InverseUndisturbed gens1 e2) (hu21 : InverseUndisturbed gens2 e1) :
    Independent e1 e2 gens1 gens2 :=
  { commute := commuting_of_generators_commuting hcomm
    undisturbed12 := hu12
    undisturbed21 := hu21 }

/-- Theorem 20 / Corollary 21, the two-effect case: given `e1`, `e2`
independent (`h`), reverting the trajectory `e2.fwd (e1.fwd s0)` in a
NON-LIFO order -- undo `e1` FIRST, directly against the fully-applied
trajectory, using `e1.inv (e2.fwd s0)` (the inverse indexed by the
PRE-`e2` state `e2.fwd s0`, never touching the LIFO midpoint
`e1.fwd s0` a stack-based undo would insist on visiting), THEN undo
`e2` with its own ordinary `left_inv` -- reaches `s0` exactly. This is
Corollary 21's real content, proved from `InverseUndisturbed gens2 e1`
(Definition 19 clause b) alone: applying `e2.fwd` (a monoid element of
`gens2`) never disturbs what `e1.inv` at the pre-`e2` state can
correctly undo about `e1`'s own later effect, so the two-step (undo e1
through e2's still-standing effect, then undo e2) genuinely different
reversion order than `revertLifo2_correct` below (which needs no
independence hypothesis and always works) lands on the same exact
initial state. -/
theorem independent_pair_revert_nonlifo_order
    (e1 e2 : RevertibleEffect Gamma) (gens1 gens2 : List (Gamma → Gamma))
    (h : Independent e1 e2 gens1 gens2)
    (hg2 : e2.fwd ∈ gens2) (s0 : Gamma) :
    -- Step 1 (undo e1 FIRST, "through" e2's still-standing effect,
    -- rather than waiting for e2 to be undone first as LIFO order
    -- requires): `InverseUndisturbed` guarantees e1's inverse at the
    -- pre-e2 state `e2.fwd s0`, applied to the fully-applied
    -- trajectory, lands exactly on `e2.fwd s0` -- e1's own effect is
    -- fully removed even though e2.fwd was never touched.
    e1.inv (e2.fwd s0) (e2.fwd (e1.fwd s0)) = e2.fwd s0 ∧
    -- Step 2 (undo e2, ordinary `left_inv`, no independence needed):
    -- applied to Step 1's result, reaches s0 exactly, completing the
    -- non-LIFO reversion.
    e2.inv s0 (e2.fwd s0) = s0 := by
  refine ⟨?_, e2.left_inv s0⟩
  have hund : e1.inv (e2.fwd s0) (e2.fwd (e1.fwd s0)) = e2.fwd (e1.inv s0 (e1.fwd s0)) :=
    h.undisturbed21 e2.fwd (InMonoid.gen e2.fwd hg2) s0 (e1.fwd s0)
  rw [e1.left_inv] at hund
  exact hund

/-- The ordinary LIFO/stack reversion order (undo `e2`, the
last-applied effect, first; then undo `e1`) reaches `s0` exactly for
ANY two revertible effects -- no independence hypothesis needed. This
is the baseline `independent_pair_revert_nonlifo_order` above is
compared against: Corollary 21's content is that independence adds a
SECOND, non-LIFO route to the same exact destination, not that it is
needed for the LIFO route itself. -/
theorem revertLifo2_correct (e1 e2 : RevertibleEffect Gamma) (s0 : Gamma) :
    e1.inv s0 (e2.inv (e1.fwd s0) (e2.fwd (e1.fwd s0))) = s0 := by
  rw [e2.left_inv]
  exact e1.left_inv s0

/-- Applying every effect in a list, in list order, left to right,
starting from `s0` -- the forward trajectory a whole family's
reversion (below) undoes. -/
def applyAll (effects : List (RevertibleEffect Gamma)) (s0 : Gamma) : Gamma :=
  effects.foldl (fun s e => e.fwd s) s0

/-- Reverting a list of effects that were applied via `applyAll`, in
LIST order (head first) rather than reverse-application order --
`revertHeadFirst [] s0 = s0`; `revertHeadFirst (e :: rest) s0` first
finishes reverting `rest` against the trajectory's own tail, THEN
undoes `e` using the state that reversion left at, via `e.inv`
evaluated at the ORIGINAL pre-`e` state (the second argument tracks
what state `e.fwd` actually started from, needed because `inv` is
state-indexed). This is the general n-ary reversal-order machinery:
`revertLifo2_correct`/`independent_pair_revert_nonlifo_order` above are
its two n=2 instances (reverting `[e2,e1]`-order vs `[e1,e2]`-order
against the same forward trajectory). The genuinely order-parametric
n-ary statement (Theorem 20's full strength: EVERY permutation, not
just these two named orders) is `IndependenceNAry.lean`'s
`corollary21` -- proved there via a `PairwiseFamily`-shaped downward
induction over a permutation list rather than by generalizing this
file's own `revertHeadFirst`/state-indexing directly, since the fixed
per-position state trace this definition tracks does not by itself
generalize to an arbitrary permutation's own intermediate states. -/
def revertHeadFirst (effects : List (RevertibleEffect Gamma)) (preStates : List Gamma)
    (finalState : Gamma) : Gamma :=
  match effects, preStates with
  | [], _ => finalState
  | _, [] => finalState
  | e :: erest, s :: srest => e.inv s (revertHeadFirst erest srest finalState)

/-- `revertHeadFirst` correctly undoes a two-element list `[e1, e2]`
applied via `applyAll` from `s0`, reverting in LIST order (the general
`revertHeadFirst` machinery's own traversal order: `e1`'s entry is
processed first in the match, so its `inv` call wraps the whole
expression outermost, deferring to the recursive call on `[e2]` for the
rest -- this reduces to exactly `revertLifo2_correct`'s LIFO order,
requiring no independence hypothesis, since undoing the OUTER-wrapped
first-list-entry last is definitionally the same as undoing the
last-applied effect first). This shows `revertHeadFirst`/`applyAll`
agree with the earlier direct development; the genuinely independence-
dependent non-LIFO order is `independent_pair_revert_nonlifo_order`
above, not reachable via `revertHeadFirst`'s fixed list-order
traversal alone. -/
theorem revertHeadFirst_pair (e1 e2 : RevertibleEffect Gamma) (s0 : Gamma) :
    revertHeadFirst [e1, e2] [s0, e1.fwd s0] (applyAll [e1, e2] s0) = s0 := by
  show e1.inv s0 (e2.inv (e1.fwd s0) (revertHeadFirst [] [] (applyAll [e1, e2] s0))) = s0
  show e1.inv s0 (e2.inv (e1.fwd s0) (applyAll [e1, e2] s0)) = s0
  have hfinal : applyAll [e1, e2] s0 = e2.fwd (e1.fwd s0) := by
    simp [applyAll, List.foldl]
  rw [hfinal, e2.left_inv]
  exact e1.left_inv s0

/-- A well-formedness hypothesis every finite family of effects
reasoned about together must state explicitly (the way Theorem
66/73's own precedence-acyclicity hypothesis is external, per this
project's `AGENTS.md` caution about the earlier deadlock incident from
an unenforced acyclicity assumption): pairwise independence between
every DISTINCT pair the family names. This is Definition 19's own
scope -- independence is stated pairwise, never claimed for a triple or
larger group directly -- so a family-level structure exposes this as an
explicit field rather than silently assuming it from independence
between just two members. No larger-arity independence notion is
defined or assumed anywhere in this file. -/
structure PairwiseIndependentPair (Gamma : Type) where
  e1 : RevertibleEffect Gamma
  e2 : RevertibleEffect Gamma
  gens1 : List (Gamma → Gamma)
  gens2 : List (Gamma → Gamma)
  indep : Independent e1 e2 gens1 gens2
  gen1_has_fwd : e1.fwd ∈ gens1
  gen2_has_fwd : e2.fwd ∈ gens2

/-- Corollary 21 restated at the `PairwiseIndependentPair` bundle: both
the LIFO order and the non-LIFO order reach the pair's shared starting
state `s0` exactly -- packaging the two theorems above as the single
fact a caller cites once the well-formedness bundle is in hand. -/
theorem PairwiseIndependentPair.revert_both_orders
    (p : PairwiseIndependentPair Gamma) (s0 : Gamma) :
    (p.e1.inv s0 (p.e2.inv (p.e1.fwd s0) (p.e2.fwd (p.e1.fwd s0))) = s0) ∧
    (p.e1.inv (p.e2.fwd s0) (p.e2.fwd (p.e1.fwd s0)) = p.e2.fwd s0 ∧
     p.e2.inv s0 (p.e2.fwd s0) = s0) :=
  ⟨revertLifo2_correct p.e1 p.e2 s0,
   independent_pair_revert_nonlifo_order p.e1 p.e2 p.gens1 p.gens2 p.indep p.gen2_has_fwd s0⟩
